// ============================================================
// ==================== СИСТЕМА ЛОКАЛИЗАЦИИ ===================
// ============================================================

const TRANSLATIONS = {
    ru: {
        settings: 'Настройки',
        language: 'Язык',
        close: 'Закрыть',
        music: 'Музыка',

        balance: '$RAT',
        click: 'Клик',
        passive: 'Пассив',
        perSec: '/сек',
        buffActive: '⚡ x2 БУСТ АКТИВЕН!',
        autoClick: 'Авто-клик',

        autoFertilizerBadge: '🤖 Удобрения',
        autoClickBadge: '🤖 Авто-клик',
        autoCollect: 'Авто-сбор',

        grainToggle: '🌽 Зерно',
        superGrainToggle: '⭐ Супер',
        mouseToggle: '🐁 Мышь',
        toggleOn: 'Вкл',
        toggleOff: 'Выкл',
        toggleLevel: 'Ур.',
        superGrainBase: 'Базовое: 25',
        superIndicatorOff: '⚠️ Включите оба!',
        mouseIndicatorNoGrain: '⚠️ Нет зерна',

        shop: 'Крысиный магазин',
        shopBtn: '🛒 МАГАЗИН',
        tabBoosts: 'Бусты',
        tabAccessories: 'Аксессуары',
        tabBosses: '💀 Боссы',

        buy: 'Купить',
        upgrade: 'Улучшить',
        max: 'MAX',
        bought: 'Куплено',
        price: 'Цена',
        level: 'Уровень',
        cost: 'Стоимость',

        clickBoost: '🌾 Больше зерна',
        clickBoostDesc: 'Увеличивает силу клика на +1',

        autoBoost: '🍔 Ожирение',
        autoBoostDesc: 'Даёт +1 пассивный доход каждую секунду',
        autoBoostHint1: '🔓 10 уровней открывают новые прокачки',
        autoBoostHint2: '⬆️ Оставшиеся 10 можно докачать позже',

        grain: '🌽 Зерно',
        grainDesc: 'КЛИКНИ по зерну! Базовое значение',
        grainTimesClick: '× сила клика',
        grainUpgradePrice: 'Цена улучшения',
        grainLevel: 'Уровень',
        grainHint: '⚡ После покупки появится тумблер справа',

        superGrain: '⭐ Супер зерно',
        superGrainDesc: 'КЛИКНИ по зерну! Базовое значение: 25 × сила клика',
        superGrainSpawn: 'Спавнится в 2 раза реже обычного',
        superGrainOnce: '⭐ УЛУЧШЕННОЕ (покупается 1 раз)',
        superGrainHint1: '⚡ После покупки появится второй тумблер',
        superGrainHint2: '🌾 Лимит "Больше зерна" увеличится до 20',
        superGrainHint3: '🔗 Для работы супер-зерна нужны оба тумблера!',
        superGrainHint4: '🐁 Откроется мышь-собиратор в магазине!',

        mouse: '🐁 Мышь-собиратор',
        mouseDesc: 'Автоматически собирает зерно с экрана!',
        mouseDesc2: 'Бегает по экрану и забирает зерно за вас',
        mouseOnce: '🐁 УЛУЧШЕНИЕ (покупается 1 раз)',
        mouseHint: '⚡ После покупки появится тумблер мыши',

        hamsters: '🐹 Морские свинки',
        hamstersDesc: 'Милые свинки в вольере! Дают бонус к силе клика',
        hamstersOnce: '🐹 УЛУЧШЕНИЕ (покупается 1 раз)',
        hamstersHint: '⚡ После покупки появится вольер слева',
        hamsterUpgrade: '⬆️ Улучшить свинок',
        hamsterUpgradeDesc: 'Увеличивает бонус от морских свинок',
        hamsterCurrentBonus: 'Текущий бонус',

        potFirst: '🌱 Первый горшок',
        potFirstDesc: 'Растение в горшке!',
        potFirstHint: '🌿 Даёт 1 растение в инвентарь после сбора',
        potOnce: '🌱 УЛУЧШЕНИЕ (покупается 1 раз)',
        potHint: '⚡ После покупки появится горшок слева внизу',
        potHintReq: '🔒 Требуется 1+ уровень свинок!',
        potUpgrade1: '⬆️ Улучшение горшков I',
        potUpgrade1Desc: 'Добавляет второй горшок',
        potUpgrade1Level: '🌱 УРОВЕНЬ 2',
        potUpgrade2: '⬆️ Улучшение горшков II',
        potUpgrade2Desc: 'Добавляет третий горшок',
        potUpgrade2Level: '🌱 УРОВЕНЬ 3 (МАКСИМУМ)',

        grass: '🌿 Трава',
        grassDesc: 'Растёт 3 минуты. Кормит свинок на 100%',
        pepper: '🌶️ Болгарский перец',
        pepperDesc: 'Растёт 5 минут. Кормит на 100% + x2 буст свинкам на 30 сек',
        apple: '🍎 Яблоко',
        appleDesc: 'Растёт 8 минут. Кормит на 100% + насыщение 1 минуту',
        appleHint: '🍽️ Свинки НЕ тратят голод 1 минуту',
        cabbage: '🥬 Капуста',
        cabbageDesc: 'Растёт 2 минуты. Насыщает на 50% + 💩 5 какашек',
        plantOnce: '(покупается 1 раз)',

        lab: '🧪 Лаборатория',
        labDesc: 'Полноценная лаборатория для исследований!',
        labOnce: '🧪 УЛУЧШЕНИЕ (покупается 1 раз)',
        labHint1: '⚡ После покупки появится кнопка "ЛАБОРАТОРИЯ"',
        labHint2: '⚙️ В лаборатории доступны разные устройства',

        combiner: '🧪 Комбинатор',
        combinerDesc: 'Большой крафтовый стол для создания новых предметов!',
        combinerSlots: '📦 2 слота для крафта',
        combinerRecipe1: '🟢 Экстракт ГМО яблока = Яблоко + Удобрение (5 мин)',
        combinerRecipe2: '🔴 Экстракт корма = Яблоко + Трава + Перец (5 мин)',
        combinerRecipe3: '🟡 Экстракт сена = Трава + Трава (3 мин)',
        combinerOnce: '🧪 УЛУЧШЕНИЕ (покупается 1 раз)',
        combinerHint: '⚡ После покупки появится вкладка "Комбинатор"',
        combinerUpgrade: '⬆️ Улучшить комбинатор',
        combinerUpgradeDesc: 'Добавляет 3-й слот для крафта',
        combinerCurrentLevel: 'Текущий уровень',
        combinerLevel1: 'Уровень 1 (2 слота)',
        combinerLevel2: 'Уровень 2 (3 слота)',

        extractor: '⚗️ Аппарат превращения',
        extractorDesc: 'Превращает экстракты в готовые предметы!',
        extractorTime: '⏱️ 1 минута на превращение',
        extractorRecipe1: '🟢 Экстракт ГМО яблока → 🍏 ГМО яблоко',
        extractorRecipe2: '🔴 Экстракт крысиного корма → 🍖 Крысиный корм',
        extractorRecipe3: '🟡 Экстракт сена → 🌾 Сено',
        extractorNoUpgrade: '⚗️ НЕ УЛУЧШАЕТСЯ',

        gmoAppleExtract: '🟢 Экстракт ГМО яблока',
        ratFoodExtract: '🔴 Экстракт крысиного корма',
        hayExtract: '🟡 Экстракт сена',

        manipulator: '🤖 Манипулятор',
        manipulatorDesc: 'Автоматизированный робот для работы в лаборатории!',
        manipulatorHint1: '⚙️ Настраивается под любую задачу',
        manipulatorHint2: '🍖 Кормит свинок',
        manipulatorHint3: '🔧 Автоматически крафтит',
        manipulatorHint4: '🧪 Делает удобрения',
        manipulatorHint5: '🌱 Выращивает растения',
        manipulatorHint6: '🎯 Кликает по крысе',
        manipulatorBought: 'Куплено',
        manipulatorHint7: '⚡ После покупки появится тумблер справа',
        manipulatorHint8: '🔒 Требуются все части лаборатории!',

        advancedLogic: '🧠 Улучшенная логика манипуляторов',
        advancedLogicDesc: 'Прокачка для манипуляторов!',
        advancedLogicHint1: '⚙️ Настройка интервала работы: 5 / 10 / 30 / 60 сек',
        advancedLogicHint2: '🎯 Условия: "если меньше N" и "если больше N"',
        advancedLogicHint3: '🔢 Настройка порога от 1 до 100',
        advancedLogicHint4: '🎯 Новое действие: авто-клик по крысе',
        advancedLogicOnce: '🧠 УЛУЧШЕНИЕ (покупается 1 раз)',
        advancedLogicHint5: '🔒 Требуется хотя бы 1 манипулятор',

        hat: 'Шляпа мафиози',
        hatDesc: 'Стильная шляпа для солидной крысы',
        glasses: 'Крутые очки',
        glassesDesc: 'Чтобы скрыть свои тёмные дела',
        sword: 'Меч ниндзя',
        swordDesc: 'Для защиты от котов и других врагов',
        crown: 'Корона крыс',
        crownDesc: 'Только для истинного короля грызунов',
        bonus: 'Бонус',
        activeBonus: 'Активный бонус',
        wear: 'Надеть',
        remove: 'Снять',

        bossMenu: '💀 Меню боссов',
        bossMenuDesc: 'Открывает доступ к боссам и их меню',
        bossMenuOnce: '💀 УЛУЧШЕНИЕ (покупается 1 раз)',
        bossMenuHint1: '⚡ После покупки появится череп',
        bossMenuHint2: '🦫 Боссы покупаются отдельно',
        capybara: '🦫 Капибара',
        capybaraDesc: 'Спокойный гигант, но опасный противник!',
        capybaraReward: '💰 Награда: Корм для крысы (x2 буст на 30 сек)',
        capybaraOnce: '🦫 БОСС (покупается 1 раз)',
        capybaraHint: '⚡ После покупки появится в меню боссов',
        capybaraCooldown: '⏳ Перезарядка: 10 минут',
        fightBtn: 'Сражаться',
        notBought: '🔒 Не куплен',
        ready: '⚔️ Готов к бою!',
        defeated: '✅ Побеждена!',
        cooldown: '⏳ Перезарядка',
        bossFightTitle: '⚔️ БОЙ С КАПИБАРОЙ',
        bossHP: '❤️ HP Капибары',
        shoot: '🎯 СТРЕЛЯТЬ',
        retreat: '🏃 ОТСТУПИТЬ',
        bossTimer: '⏳ До следующей попытки',
        bossesTitle: '💀 БОССЫ',

        inventory: '🎒 Инвентарь',
        inventoryEmpty: '🎒 Инвентарь пуст',
        use: 'Использовать',
        ratFood: '🍖 Корм для крысы',
        gmoApple: '🍏 ГМО яблоко',
        hay: '🌾 Сено',

        feed: '🍖 Покормить',
        collectPoop: '💩 Собрать',
        openShop: '🛒 МАГАЗИН',
        openLab: '🧪 ЛАБОРАТОРИЯ',
        openInv: '🎒 Инвентарь',

        enclosure: '🐹 ВОЛЬЕР',
        hungry: '🔴 Голодные',
        fed: '✅ Сытые',
        satiety: '🍽️ Сытость',
        satietyActive: '🍽️ Сытость активна',
        bonusLabel: '🐹 Бонус',
        feedToActivate: '(покормите!)',
        pepperBuff: '🌶️ x2 БУСТ СВИНОК!',
        hayBuff: '🌾 x1.3 БУСТ СВИНОК!',

        pots: '🌱 ГОРШКИ',
        empty: 'Пусто',
        water: '💧 Полить',
        collectPlant: '✅ Собрать!',
        growing: 'растёт',

        labTitle: '🧪 ЛАБОРАТОРИЯ',
        poopLabel: '💩 Какашек',
        fertLabel: '🧪 Удобрений',
        machineName: 'Станок удобрений',
        idle: '⏸️ Бездействует',
        working: '⚙️ Работает...',
        done: '✅ Готово! Нажмите для сбора',
        start: '🔧 Запустить',
        collectFertilizer: '🧪 Собрать удобрение',
        processing: '⏳ Обработка...',
        timeLabel: '⏱️ Время',
        levelLabel: 'Уровень',
        min: 'мин',

        combinerTitle: '🧪 КОМБИНАТОР',
        putIngredients: '📋 Положите ингредиенты в слоты',
        craft: '🔧 СКРАФТИТЬ',
        crafting: 'Крафтится...',
        emptySlot: '➕ Пусто',

        extractorTitle: '⚗️ АППАРАТ ПРЕВРАЩЕНИЯ',
        queueEmpty: '⏳ Очередь пуста',

        manipSettings: '⚙️ НАСТРОЙКИ МАНИПУЛЯТОРА',
        action: 'Действие',
        interval: '⏱️ Интервал',
        condition: 'Условие',
        threshold: 'Порог',
        feedWith: 'Чем кормить',
        whatToCraft: 'Что крафтить',
        save: '💾 Сохранить',
        actionIdle: '❌ Бездействует',
        actionClickRat: '🎯 Кликать по крысе',
        actionFeedHamsters: '🍖 Кормить свинок',
        actionCraft: '🔧 Крафтить',
        actionGrowPlants: '🌱 Выращивать растения',
        actionMakeFertilizer: '🧪 Делать удобрения',
        conditionAlways: '🔁 Всегда',
        conditionBelow: '📉 Меньше N',
        conditionAbove: '📈 Больше N',
        sec5: '5 секунд',
        sec10: '10 секунд',
        sec30: '30 секунд',
        sec60: '60 секунд',

        pot1: 'Горшок 1',
        pot2: 'Горшок 2',
        pot3: 'Горшок 3',
        whatToGrow: 'Что садить',
        selectPlant: '🌱 Выберите растение:',
        selectIngredient: 'Выберите ингредиент:',
        selectPotForFertilizer: '🧪 Выберите горшок для удобрения:',
        useFertilizerConfirm: '🧪 Использовать удобрение?',
        plantHint: 'Введите номер:',

        resetTitle: '⚠️ СБРОС ПРОГРЕССА',
        resetWarning: 'ВНИМАНИЕ! Все данные будут удалены безвозвратно!',
        resetEnterCode: 'Введите код для подтверждения:',
        resetConfirm: '❗ ВЫ УВЕРЕНЫ? ❗',
        resetNoBack: 'Это действие нельзя отменить!',
        resetBtn: 'СБРОСИТЬ',
        cancel: 'Отмена',

        reloadTitle: '🔄 ПЕРЕЗАГРУЗИТЕ ИГРУ',
        reloadSuccess: 'Данные успешно сброшены!',
        reloadHint: 'Для полного применения изменений и исправления возможных багов необходимо перезагрузить страницу.',
        seconds: 'секунд',
        reloadBtn: '🔄 OK',

        notEnough: 'Не хватает монет!',
        maxLevel: 'Максимальный уровень достигнут!',
        alreadyBought: 'Уже куплено!',
        needMore: 'Нужно',
        cheatDetected: '⚠️ ОБНАРУЖЕН АВТОКЛИКЕР! ⚠️',

        alertAlreadyWorking: '⚙️ Уже работает!',
        alertNotEnoughPoop: '💩 Не хватает какашек!',
        alertExtractSent: '✅ Экстракт отправлен в аппарат!',
        alertExtractNeedExtractor: '⚠️ Нужен аппарат превращения!',
        alertMachineRunning: '⚙️ Станок уже работает!',
        alertFertilizerReady: '✅ Удобрение готово!',

        logGameVersion: '💀 Rat Coin v',
        logLanguages: '🌍 Языки: RU / EN / UK',
        logLangChanged: '🌍 Язык изменён на:',
        logEnvInit: '🔧 Окружение инициализировано. Язык:',
        logRestore: '🔄 Восстановление...',
        logRestored: '✅ Восстановлено!',
        logMultiTabBlocked: '🚫 Мультивкладка заблокирована',
        logCheatBlocked: '🔒 Команда заблокирована:',
    },

    en: {
        settings: 'Settings',
        language: 'Language',
        close: 'Close',
        music: 'Music',

        balance: '$RAT',
        click: 'Click',
        passive: 'Passive',
        perSec: '/sec',
        buffActive: '⚡ x2 BUFF ACTIVE!',
        autoClick: 'Auto-click',

        autoFertilizerBadge: '🤖 Fertilizers',
        autoClickBadge: '🤖 Auto-click',
        autoCollect: 'Auto-collect',

        grainToggle: '🌽 Grain',
        superGrainToggle: '⭐ Super',
        mouseToggle: '🐁 Mouse',
        toggleOn: 'ON',
        toggleOff: 'OFF',
        toggleLevel: 'Lv.',
        superGrainBase: 'Base: 25',
        superIndicatorOff: '⚠️ Enable both!',
        mouseIndicatorNoGrain: '⚠️ No grain',

        shop: 'Rat Shop',
        shopBtn: '🛒 SHOP',
        tabBoosts: 'Boosts',
        tabAccessories: 'Accessories',
        tabBosses: '💀 Bosses',

        buy: 'Buy',
        upgrade: 'Upgrade',
        max: 'MAX',
        bought: 'Bought',
        price: 'Price',
        level: 'Level',
        cost: 'Cost',

        clickBoost: '🌾 More Grain',
        clickBoostDesc: 'Increases click power by +1',

        autoBoost: '🍔 Obesity',
        autoBoostDesc: 'Gives +1 passive income every second',
        autoBoostHint1: '🔓 10 levels unlock new upgrades',
        autoBoostHint2: '⬆️ The remaining 10 can be finished later',

        grain: '🌽 Grain',
        grainDesc: 'CLICK the grain! Base value',
        grainTimesClick: '× click power',
        grainUpgradePrice: 'Upgrade price',
        grainLevel: 'Level',
        grainHint: '⚡ A toggle will appear on the right after purchase',

        superGrain: '⭐ Super Grain',
        superGrainDesc: 'CLICK the grain! Base value: 25 × click power',
        superGrainSpawn: 'Spawns 2 times less often than usual',
        superGrainOnce: '⭐ ENHANCED (one-time purchase)',
        superGrainHint1: '⚡ A second toggle will appear',
        superGrainHint2: '🌾 "More Grain" limit increases to 20',
        superGrainHint3: '🔗 Both toggles required for super grain!',
        superGrainHint4: '🐁 Mouse collector will appear in shop!',

        mouse: '🐁 Mouse Collector',
        mouseDesc: 'Automatically collects grain from screen!',
        mouseDesc2: 'Runs around the screen and collects grain for you',
        mouseOnce: '🐁 UPGRADE (one-time purchase)',
        mouseHint: '⚡ A mouse toggle will appear after purchase',

        hamsters: '🐹 Guinea Pigs',
        hamstersDesc: 'Cute piggies in the enclosure! Give click power bonus',
        hamstersOnce: '🐹 UPGRADE (one-time purchase)',
        hamstersHint: '⚡ An enclosure will appear on the left',
        hamsterUpgrade: '⬆️ Upgrade Piggies',
        hamsterUpgradeDesc: 'Increases guinea pigs bonus',
        hamsterCurrentBonus: 'Current bonus',

        potFirst: '🌱 First Pot',
        potFirstDesc: 'Plant in a pot!',
        potFirstHint: '🌿 Gives 1 plant to inventory after harvest',
        potOnce: '🌱 UPGRADE (one-time purchase)',
        potHint: '⚡ A pot will appear at bottom left',
        potHintReq: '🔒 Requires 1+ hamster level!',
        potUpgrade1: '⬆️ Pot Upgrade I',
        potUpgrade1Desc: 'Adds a second pot',
        potUpgrade1Level: '🌱 LEVEL 2',
        potUpgrade2: '⬆️ Pot Upgrade II',
        potUpgrade2Desc: 'Adds a third pot',
        potUpgrade2Level: '🌱 LEVEL 3 (MAX)',

        grass: '🌿 Grass',
        grassDesc: 'Grows in 3 minutes. Feeds piggies to 100%',
        pepper: '🌶️ Bell Pepper',
        pepperDesc: 'Grows in 5 minutes. Feeds to 100% + x2 boost to piggies for 30 sec',
        apple: '🍎 Apple',
        appleDesc: 'Grows in 8 minutes. Feeds to 100% + satiety for 1 minute',
        appleHint: '🍽️ Piggies do NOT lose hunger for 1 minute',
        cabbage: '🥬 Cabbage',
        cabbageDesc: 'Grows in 2 minutes. Feeds by 50% + 💩 5 poops',
        plantOnce: '(one-time purchase)',

        lab: '🧪 Laboratory',
        labDesc: 'Full laboratory for research!',
        labOnce: '🧪 UPGRADE (one-time purchase)',
        labHint1: '⚡ "LABORATORY" button will appear',
        labHint2: '⚙️ Various devices available inside',

        combiner: '🧪 Combiner',
        combinerDesc: 'Big crafting table for new items!',
        combinerSlots: '📦 2 crafting slots',
        combinerRecipe1: '🟢 GMO Apple Extract = Apple + Fertilizer (5 min)',
        combinerRecipe2: '🔴 Food Extract = Apple + Grass + Pepper (5 min)',
        combinerRecipe3: '🟡 Hay Extract = Grass + Grass (3 min)',
        combinerOnce: '🧪 UPGRADE (one-time purchase)',
        combinerHint: '⚡ "Combiner" tab will appear in laboratory',
        combinerUpgrade: '⬆️ Upgrade Combiner',
        combinerUpgradeDesc: 'Adds 3rd crafting slot',
        combinerCurrentLevel: 'Current level',
        combinerLevel1: 'Level 1 (2 slots)',
        combinerLevel2: 'Level 2 (3 slots)',

        extractor: '⚗️ Extractor',
        extractorDesc: 'Turns extracts into finished items!',
        extractorTime: '⏱️ 1 minute per conversion',
        extractorRecipe1: '🟢 GMO Apple Extract → 🍏 GMO Apple',
        extractorRecipe2: '🔴 Rat Food Extract → 🍖 Rat Food',
        extractorRecipe3: '🟡 Hay Extract → 🌾 Hay',
        extractorNoUpgrade: '⚗️ NOT UPGRADABLE',

        gmoAppleExtract: '🟢 GMO Apple Extract',
        ratFoodExtract: '🔴 Rat Food Extract',
        hayExtract: '🟡 Hay Extract',

        manipulator: '🤖 Manipulator',
        manipulatorDesc: 'Automated robot for laboratory work!',
        manipulatorHint1: '⚙️ Configurable for any task',
        manipulatorHint2: '🍖 Feeds piggies',
        manipulatorHint3: '🔧 Crafts automatically',
        manipulatorHint4: '🧪 Makes fertilizers',
        manipulatorHint5: '🌱 Grows plants',
        manipulatorHint6: '🎯 Clicks the rat',
        manipulatorBought: 'Bought',
        manipulatorHint7: '⚡ A toggle will appear on the right',
        manipulatorHint8: '🔒 All lab parts required!',

        advancedLogic: '🧠 Advanced Manipulator Logic',
        advancedLogicDesc: 'Manipulator upgrade!',
        advancedLogicHint1: '⚙️ Interval setting: 5 / 10 / 30 / 60 sec',
        advancedLogicHint2: '🎯 Conditions: "if less than N" and "if more than N"',
        advancedLogicHint3: '🔢 Threshold setting from 1 to 100',
        advancedLogicHint4: '🎯 New action: auto-click the rat',
        advancedLogicOnce: '🧠 UPGRADE (one-time purchase)',
        advancedLogicHint5: '🔒 Requires at least 1 manipulator',

        hat: 'Mafia Hat',
        hatDesc: 'Stylish hat for a solid rat',
        glasses: 'Cool Glasses',
        glassesDesc: 'To hide your dark deeds',
        sword: 'Ninja Sword',
        swordDesc: 'For protection from cats and other enemies',
        crown: 'Rat Crown',
        crownDesc: 'Only for the true king of rodents',
        bonus: 'Bonus',
        activeBonus: 'Active bonus',
        wear: 'Wear',
        remove: 'Remove',

        bossMenu: '💀 Boss Menu',
        bossMenuDesc: 'Unlocks bosses and their menu',
        bossMenuOnce: '💀 UPGRADE (one-time purchase)',
        bossMenuHint1: '⚡ A skull will appear after purchase',
        bossMenuHint2: '🦫 Bosses are purchased separately',
        capybara: '🦫 Capybara',
        capybaraDesc: 'Calm giant, but dangerous opponent!',
        capybaraReward: '💰 Reward: Rat Food (x2 boost for 30 sec)',
        capybaraOnce: '🦫 BOSS (one-time purchase)',
        capybaraHint: '⚡ Will appear in boss menu after purchase',
        capybaraCooldown: '⏳ Cooldown: 10 minutes',
        fightBtn: 'Fight',
        notBought: '🔒 Not bought',
        ready: '⚔️ Ready to fight!',
        defeated: '✅ Defeated!',
        cooldown: '⏳ Cooldown',
        bossFightTitle: '⚔️ FIGHT WITH CAPYBARA',
        bossHP: '❤️ Capybara HP',
        shoot: '🎯 SHOOT',
        retreat: '🏃 RETREAT',
        bossTimer: '⏳ Next attempt in',
        bossesTitle: '💀 BOSSES',

        inventory: '🎒 Inventory',
        inventoryEmpty: '🎒 Inventory is empty',
        use: 'Use',
        ratFood: '🍖 Rat Food',
        gmoApple: '🍏 GMO Apple',
        hay: '🌾 Hay',

        feed: '🍖 Feed',
        collectPoop: '💩 Collect',
        openShop: '🛒 SHOP',
        openLab: '🧪 LABORATORY',
        openInv: '🎒 Inventory',

        enclosure: '🐹 ENCLOSURE',
        hungry: '🔴 Hungry',
        fed: '✅ Fed',
        satiety: '🍽️ Satiety',
        satietyActive: '🍽️ Satiety active',
        bonusLabel: '🐹 Bonus',
        feedToActivate: '(feed them!)',
        pepperBuff: '🌶️ x2 PIGGY BOOST!',
        hayBuff: '🌾 x1.3 PIGGY BOOST!',

        pots: '🌱 POTS',
        empty: 'Empty',
        water: '💧 Water',
        collectPlant: '✅ Collect!',
        growing: 'growing',

        labTitle: '🧪 LABORATORY',
        poopLabel: '💩 Poops',
        fertLabel: '🧪 Fertilizers',
        machineName: 'Fertilizer Machine',
        idle: '⏸️ Idle',
        working: '⚙️ Working...',
        done: '✅ Done! Click to collect',
        start: '🔧 Start',
        collectFertilizer: '🧪 Collect fertilizer',
        processing: '⏳ Processing...',
        timeLabel: '⏱️ Time',
        levelLabel: 'Level',
        min: 'min',

        combinerTitle: '🧪 COMBINER',
        putIngredients: '📋 Put ingredients in slots',
        craft: '🔧 CRAFT',
        crafting: 'Crafting...',
        emptySlot: '➕ Empty',

        extractorTitle: '⚗️ EXTRACTOR',
        queueEmpty: '⏳ Queue is empty',

        manipSettings: '⚙️ MANIPULATOR SETTINGS',
        action: 'Action',
        interval: '⏱️ Interval',
        condition: 'Condition',
        threshold: 'Threshold',
        feedWith: 'Feed with',
        whatToCraft: 'What to craft',
        save: '💾 Save',
        actionIdle: '❌ Idle',
        actionClickRat: '🎯 Click the rat',
        actionFeedHamsters: '🍖 Feed piggies',
        actionCraft: '🔧 Craft',
        actionGrowPlants: '🌱 Grow plants',
        actionMakeFertilizer: '🧪 Make fertilizers',
        conditionAlways: '🔁 Always',
        conditionBelow: '📉 Less than N',
        conditionAbove: '📈 More than N',
        sec5: '5 seconds',
        sec10: '10 seconds',
        sec30: '30 seconds',
        sec60: '60 seconds',

        pot1: 'Pot 1',
        pot2: 'Pot 2',
        pot3: 'Pot 3',
        whatToGrow: 'What to grow',
        selectPlant: '🌱 Select a plant:',
        selectIngredient: 'Select ingredient:',
        selectPotForFertilizer: '🧪 Select a pot for fertilizer:',
        useFertilizerConfirm: '🧪 Use fertilizer?',
        plantHint: 'Enter number:',

        resetTitle: '⚠️ RESET PROGRESS',
        resetWarning: 'WARNING! All data will be permanently deleted!',
        resetEnterCode: 'Enter confirmation code:',
        resetConfirm: '❗ ARE YOU SURE? ❗',
        resetNoBack: 'This action cannot be undone!',
        resetBtn: 'RESET',
        cancel: 'Cancel',

        reloadTitle: '🔄 RELOAD GAME',
        reloadSuccess: 'Data successfully reset!',
        reloadHint: 'Reload the page to fully apply changes and fix possible bugs.',
        seconds: 'seconds',
        reloadBtn: '🔄 OK',

        notEnough: 'Not enough coins!',
        maxLevel: 'Maximum level reached!',
        alreadyBought: 'Already bought!',
        needMore: 'Need',
        cheatDetected: '⚠️ AUTOCLICKER DETECTED! ⚠️',

        alertAlreadyWorking: '⚙️ Already working!',
        alertNotEnoughPoop: '💩 Not enough poops!',
        alertExtractSent: '✅ Extract sent to the machine!',
        alertExtractNeedExtractor: '⚠️ Extractor required!',
        alertMachineRunning: '⚙️ Machine is already running!',
        alertFertilizerReady: '✅ Fertilizer is ready!',

        logGameVersion: '💀 Rat Coin v',
        logLanguages: '🌍 Languages: RU / EN / UK',
        logLangChanged: '🌍 Language changed to:',
        logEnvInit: '🔧 Environment initialized. Language:',
        logRestore: '🔄 Restoring...',
        logRestored: '✅ Restored!',
        logMultiTabBlocked: '🚫 Multi-tab blocked',
        logCheatBlocked: '🔒 Command blocked:',
    },

    uk: {
        settings: 'Налаштування',
        language: 'Мова',
        close: 'Закрити',
        music: 'Музика',

        balance: '$RAT',
        click: 'Клік',
        passive: 'Пасив',
        perSec: '/сек',
        buffActive: '⚡ x2 БУСТ АКТИВНИЙ!',
        autoClick: 'Авто-клік',

        autoFertilizerBadge: '🤖 Добрива',
        autoClickBadge: '🤖 Авто-клік',
        autoCollect: 'Авто-збір',

        grainToggle: '🌽 Зерно',
        superGrainToggle: '⭐ Супер',
        mouseToggle: '🐁 Мишка',
        toggleOn: 'Вкл',
        toggleOff: 'Вимк',
        toggleLevel: 'Рів.',
        superGrainBase: 'Базове: 25',
        superIndicatorOff: '⚠️ Увімкніть обидва!',
        mouseIndicatorNoGrain: '⚠️ Немає зерна',

        shop: 'Щурячий магазин',
        shopBtn: '🛒 МАГАЗИН',
        tabBoosts: 'Бусти',
        tabAccessories: 'Аксесуари',
        tabBosses: '💀 Боси',

        buy: 'Купити',
        upgrade: 'Покращити',
        max: 'MAX',
        bought: 'Куплено',
        price: 'Ціна',
        level: 'Рівень',
        cost: 'Вартість',

        clickBoost: '🌾 Більше зерна',
        clickBoostDesc: 'Збільшує силу кліку на +1',

        autoBoost: '🍔 Ожиріння',
        autoBoostDesc: 'Дає +1 пасивний дохід щосекунди',
        autoBoostHint1: '🔓 10 рівнів відкривають нові прокачки',
        autoBoostHint2: '⬆️ Решту 10 можна докачати пізніше',

        grain: '🌽 Зерно',
        grainDesc: 'КЛІКНИ по зерну! Базове значення',
        grainTimesClick: '× сила кліку',
        grainUpgradePrice: 'Ціна покращення',
        grainLevel: 'Рівень',
        grainHint: '⚡ Після покупки з\'явиться перемикач справа',

        superGrain: '⭐ Супер зерно',
        superGrainDesc: 'КЛІКНИ по зерну! Базове значення: 25 × сила кліку',
        superGrainSpawn: 'З\'являється вдвічі рідше',
        superGrainOnce: '⭐ ПОКРАЩЕНЕ (купується 1 раз)',
        superGrainHint1: '⚡ Після покупки з\'явиться другий перемикач',
        superGrainHint2: '🌾 Ліміт "Більше зерна" зросте до 20',
        superGrainHint3: '🔗 Потрібні обидва перемикачі!',
        superGrainHint4: '🐁 Мишка-збирач з\'явиться в магазині!',

        mouse: '🐁 Мишка-збирач',
        mouseDesc: 'Автоматично збирає зерно з екрану!',
        mouseDesc2: 'Бігає по екрану і забирає зерно за вас',
        mouseOnce: '🐁 ПОКРАЩЕННЯ (купується 1 раз)',
        mouseHint: '⚡ Після покупки з\'явиться перемикач мишки',

        hamsters: '🐹 Морські свинки',
        hamstersDesc: 'Милі свинки у вольєрі! Дають бонус до сили кліку',
        hamstersOnce: '🐹 ПОКРАЩЕННЯ (купується 1 раз)',
        hamstersHint: '⚡ Після покупки з\'явиться вольєр зліва',
        hamsterUpgrade: '⬆️ Покращити свинок',
        hamsterUpgradeDesc: 'Збільшує бонус від морських свинок',
        hamsterCurrentBonus: 'Поточний бонус',

        potFirst: '🌱 Перший горщик',
        potFirstDesc: 'Рослина в горщику!',
        potFirstHint: '🌿 Дає 1 рослину в інвентар після збору',
        potOnce: '🌱 ПОКРАЩЕННЯ (купується 1 раз)',
        potHint: '⚡ Після покупки з\'явиться горщик зліва внизу',
        potHintReq: '🔒 Потрібен 1+ рівень свинок!',
        potUpgrade1: '⬆️ Покращення горщиків I',
        potUpgrade1Desc: 'Додає другий горщик',
        potUpgrade1Level: '🌱 РІВЕНЬ 2',
        potUpgrade2: '⬆️ Покращення горщиків II',
        potUpgrade2Desc: 'Додає третій горщик',
        potUpgrade2Level: '🌱 РІВЕНЬ 3 (МАКСИМУМ)',

        grass: '🌿 Трава',
        grassDesc: 'Росте 3 хвилини. Годує свинок на 100%',
        pepper: '🌶️ Болгарський перець',
        pepperDesc: 'Росте 5 хвилин. Годує на 100% + x2 буст свинкам на 30 сек',
        apple: '🍎 Яблуко',
        appleDesc: 'Росте 8 хвилин. Годує на 100% + насичення 1 хвилину',
        appleHint: '🍽️ Свинки НЕ витрачають голод 1 хвилину',
        cabbage: '🥬 Капуста',
        cabbageDesc: 'Росте 2 хвилини. Насичує на 50% + 💩 5 какашок',
        plantOnce: '(купується 1 раз)',

        lab: '🧪 Лабораторія',
        labDesc: 'Повноцінна лабораторія для досліджень!',
        labOnce: '🧪 ПОКРАЩЕННЯ (купується 1 раз)',
        labHint1: '⚡ Після покупки з\'явиться кнопка "ЛАБОРАТОРІЯ"',
        labHint2: '⚙️ Всередині доступні різні пристрої',

        combiner: '🧪 Комбінатор',
        combinerDesc: 'Великий крафтовий стіл для створення нових предметів!',
        combinerSlots: '📦 2 слоти для крафту',
        combinerRecipe1: '🟢 Екстракт ГМО яблука = Яблуко + Добриво (5 хв)',
        combinerRecipe2: '🔴 Екстракт корму = Яблуко + Трава + Перець (5 хв)',
        combinerRecipe3: '🟡 Екстракт сіна = Трава + Трава (3 хв)',
        combinerOnce: '🧪 ПОКРАЩЕННЯ (купується 1 раз)',
        combinerHint: '⚡ Після покупки з\'явиться вкладка "Комбінатор"',
        combinerUpgrade: '⬆️ Покращити комбінатор',
        combinerUpgradeDesc: 'Додає 3-й слот для крафту',
        combinerCurrentLevel: 'Поточний рівень',
        combinerLevel1: 'Рівень 1 (2 слоти)',
        combinerLevel2: 'Рівень 2 (3 слоти)',

        extractor: '⚗️ Апарат перетворення',
        extractorDesc: 'Перетворює екстракти в готові предмети!',
        extractorTime: '⏱️ 1 хвилина на перетворення',
        extractorRecipe1: '🟢 Екстракт ГМО яблука → 🍏 ГМО яблуко',
        extractorRecipe2: '🔴 Екстракт щурячого корму → 🍖 Щурячий корм',
        extractorRecipe3: '🟡 Екстракт сіна → 🌾 Сіно',
        extractorNoUpgrade: '⚗️ НЕ ПОКРАЩУЄТЬСЯ',

        gmoAppleExtract: '🟢 Екстракт ГМО яблука',
        ratFoodExtract: '🔴 Екстракт щурячого корму',
        hayExtract: '🟡 Екстракт сіна',

        manipulator: '🤖 Маніпулятор',
        manipulatorDesc: 'Автоматизований робот для роботи в лабораторії!',
        manipulatorHint1: '⚙️ Налаштовується під будь-яке завдання',
        manipulatorHint2: '🍖 Годує свинок',
        manipulatorHint3: '🔧 Автоматично крафтить',
        manipulatorHint4: '🧪 Робить добрива',
        manipulatorHint5: '🌱 Вирощує рослини',
        manipulatorHint6: '🎯 Клікає по щуру',
        manipulatorBought: 'Куплено',
        manipulatorHint7: '⚡ Після покупки з\'явиться перемикач справа',
        manipulatorHint8: '🔒 Потрібні всі частини лабораторії!',

        advancedLogic: '🧠 Покращена логіка маніпуляторів',
        advancedLogicDesc: 'Прокачка для маніпуляторів!',
        advancedLogicHint1: '⚙️ Налаштування інтервалу: 5 / 10 / 30 / 60 сек',
        advancedLogicHint2: '🎯 Умови: "якщо менше N" та "якщо більше N"',
        advancedLogicHint3: '🔢 Налаштування порогу від 1 до 100',
        advancedLogicHint4: '🎯 Нова дія: авто-клік по щуру',
        advancedLogicOnce: '🧠 ПОКРАЩЕННЯ (купується 1 раз)',
        advancedLogicHint5: '🔒 Потрібен хоча б 1 маніпулятор',

        hat: 'Капелюх мафіозі',
        hatDesc: 'Стильний капелюх для солідного щура',
        glasses: 'Круті окуляри',
        glassesDesc: 'Щоб приховати свої темні справи',
        sword: 'Меч ніндзя',
        swordDesc: 'Для захисту від котів та інших ворогів',
        crown: 'Корона щурів',
        crownDesc: 'Тільки для справжнього короля гризунів',
        bonus: 'Бонус',
        activeBonus: 'Активний бонус',
        wear: 'Вдягнути',
        remove: 'Зняти',

        bossMenu: '💀 Меню босів',
        bossMenuDesc: 'Відкриває доступ до босів та їх меню',
        bossMenuOnce: '💀 ПОКРАЩЕННЯ (купується 1 раз)',
        bossMenuHint1: '⚡ Після покупки з\'явиться череп',
        bossMenuHint2: '🦫 Боси купуються окремо',
        capybara: '🦫 Капібара',
        capybaraDesc: 'Спокійний гігант, але небезпечний супротивник!',
        capybaraReward: '💰 Нагорода: Корм для щура (x2 буст на 30 сек)',
        capybaraOnce: '🦫 БОС (купується 1 раз)',
        capybaraHint: '⚡ Після покупки з\'явиться в меню босів',
        capybaraCooldown: '⏳ Перезарядка: 10 хвилин',
        fightBtn: 'Битися',
        notBought: '🔒 Не куплено',
        ready: '⚔️ Готовий до бою!',
        defeated: '✅ Переможено!',
        cooldown: '⏳ Перезарядка',
        bossFightTitle: '⚔️ БІЙ З КАПІБАРОЮ',
        bossHP: '❤️ HP Капібари',
        shoot: '🎯 СТРІЛЯТИ',
        retreat: '🏃 ВІДСТУПИТИ',
        bossTimer: '⏳ До наступної спроби',
        bossesTitle: '💀 БОСИ',

        inventory: '🎒 Інвентар',
        inventoryEmpty: '🎒 Інвентар порожній',
        use: 'Використати',
        ratFood: '🍖 Корм для щура',
        gmoApple: '🍏 ГМО яблуко',
        hay: '🌾 Сіно',

        feed: '🍖 Погодувати',
        collectPoop: '💩 Зібрати',
        openShop: '🛒 МАГАЗИН',
        openLab: '🧪 ЛАБОРАТОРІЯ',
        openInv: '🎒 Інвентар',

        enclosure: '🐹 ВОЛЬЄР',
        hungry: '🔴 Голодні',
        fed: '✅ Сити',
        satiety: '🍽️ Ситець',
        satietyActive: '🍽️ Ситець активний',
        bonusLabel: '🐹 Бонус',
        feedToActivate: '(погодуйте!)',
        pepperBuff: '🌶️ x2 БУСТ СВИНОК!',
        hayBuff: '🌾 x1.3 БУСТ СВИНОК!',

        pots: '🌱 ГОРЩИКИ',
        empty: 'Порожньо',
        water: '💧 Полити',
        collectPlant: '✅ Зібрати!',
        growing: 'росте',

        labTitle: '🧪 ЛАБОРАТОРІЯ',
        poopLabel: '💩 Какашок',
        fertLabel: '🧪 Добрив',
        machineName: 'Станок добрив',
        idle: '⏸️ Бездіє',
        working: '⚙️ Працює...',
        done: '✅ Готово! Натисніть для збору',
        start: '🔧 Запустити',
        collectFertilizer: '🧪 Зібрати добриво',
        processing: '⏳ Обробка...',
        timeLabel: '⏱️ Час',
        levelLabel: 'Рівень',
        min: 'хв',

        combinerTitle: '🧪 КОМБІНАТОР',
        putIngredients: '📋 Покладіть інгредієнти в слоти',
        craft: '🔧 СКРАФТИТИ',
        crafting: 'Крафтиться...',
        emptySlot: '➕ Порожньо',

        extractorTitle: '⚗️ АПАРАТ ПЕРЕТВОРЕННЯ',
        queueEmpty: '⏳ Черга порожня',

        manipSettings: '⚙️ НАЛАШТУВАННЯ МАНІПУЛЯТОРА',
        action: 'Дія',
        interval: '⏱️ Інтервал',
        condition: 'Умова',
        threshold: 'Поріг',
        feedWith: 'Чим годувати',
        whatToCraft: 'Що крафтити',
        save: '💾 Зберегти',
        actionIdle: '❌ Бездіє',
        actionClickRat: '🎯 Клікати по щуру',
        actionFeedHamsters: '🍖 Годувати свинок',
        actionCraft: '🔧 Крафтити',
        actionGrowPlants: '🌱 Вирощувати рослини',
        actionMakeFertilizer: '🧪 Робити добрива',
        conditionAlways: '🔁 Завжди',
        conditionBelow: '📉 Менше N',
        conditionAbove: '📈 Більше N',
        sec5: '5 секунд',
        sec10: '10 секунд',
        sec30: '30 секунд',
        sec60: '60 секунд',

        pot1: 'Горщик 1',
        pot2: 'Горщик 2',
        pot3: 'Горщик 3',
        whatToGrow: 'Що садити',
        selectPlant: '🌱 Виберіть рослину:',
        selectIngredient: 'Виберіть інгредієнт:',
        selectPotForFertilizer: '🧪 Виберіть горщик для добрива:',
        useFertilizerConfirm: '🧪 Використати добриво?',
        plantHint: 'Введіть номер:',

        resetTitle: '⚠️ СКИДАННЯ ПРОГРЕСУ',
        resetWarning: 'УВАГА! Всі дані будуть безповоротно видалені!',
        resetEnterCode: 'Введіть код для підтвердження:',
        resetConfirm: '❗ ВИ ВПЕВНЕНІ? ❗',
        resetNoBack: 'Цю дію не можна скасувати!',
        resetBtn: 'СКИНУТИ',
        cancel: 'Скасувати',

        reloadTitle: '🔄 ПЕРЕЗАВАНТАЖТЕ ГРУ',
        reloadSuccess: 'Дані успішно скинуті!',
        reloadHint: 'Перезавантажте сторінку для повного застосування змін та виправлення можливих багів.',
        seconds: 'секунд',
        reloadBtn: '🔄 OK',

        notEnough: 'Не вистачає монет!',
        maxLevel: 'Максимальний рівень досягнуто!',
        alreadyBought: 'Вже куплено!',
        needMore: 'Потрібно',
        cheatDetected: '⚠️ ВИЯВЛЕНО АВТОКЛІКЕР! ⚠️',

        alertAlreadyWorking: '⚙️ Вже працює!',
        alertNotEnoughPoop: '💩 Не вистачає какашок!',
        alertExtractSent: '✅ Екстракт відправлено в апарат!',
        alertExtractNeedExtractor: '⚠️ Потрібен апарат перетворення!',
        alertMachineRunning: '⚙️ Станок вже працює!',
        alertFertilizerReady: '✅ Добриво готове!',

        logGameVersion: '💀 Rat Coin v',
        logLanguages: '🌍 Мови: RU / EN / UK',
        logLangChanged: '🌍 Мову змінено на:',
        logEnvInit: '🔧 Середовище ініціалізовано. Мова:',
        logRestore: '🔄 Відновлення...',
        logRestored: '✅ Відновлено!',
        logMultiTabBlocked: '🚫 Мультивкладку заблоковано',
        logCheatBlocked: '🔒 Команду заблоковано:',
    }
};

let currentLang = localStorage.getItem('rat_lang') || 'ru';

function t(key) {
    if (!TRANSLATIONS[currentLang]) return TRANSLATIONS.ru[key] || key;
    return TRANSLATIONS[currentLang][key] || TRANSLATIONS.ru[key] || key;
}

function setLanguage(lang) {
    if (!TRANSLATIONS[lang]) return;
    currentLang = lang;
    window.currentLang = lang;
    localStorage.setItem('rat_lang', lang);
    document.documentElement.lang = lang;
    console.log(t('logLangChanged') + ' ' + lang);
}

function updateLangUIInternal() {
    document.querySelectorAll('.lang-item').forEach(item => {
        if (item.dataset.lang === currentLang) {
            item.classList.add('active');
        } else {
            item.classList.remove('active');
        }
    });
}

window.t = t;
window.setLanguage = setLanguage;
window.currentLang = currentLang;
window.TRANSLATIONS = TRANSLATIONS;
window.updateLangUIInternal = updateLangUIInternal;

document.documentElement.lang = currentLang;
console.log(t('logEnvInit') + ' ' + currentLang);

document.addEventListener('DOMContentLoaded', function() {
    updateLangUIInternal();
});
